### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by BritHefty** [jackjoe/mailgun_logger#14]
Using both the compose information provided and running the containers manually I get the following error when trying to access the logger:

> 17:47:03.697 [info] GET /setup
17:47:03.700 [info] Sent 500 in 3ms
17:47:03.701 [error] #PID<0.5344.0> running MailgunLoggerWeb.Endpoint (connection #PID<0.5342.0>, stream id 2) terminated
Server: 127.0.0.1:5050 (http)
Request: GET /setup
** (exit) an exception was raised:
    ** (ArgumentError) assign @view_module not available in template.
Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.
Available assigns: [:changeset, :conn, :inner_content]
        (phoenix_html 3.2.0) lib/phoenix_html/engine.ex:187: Phoenix.HTML.Engine.fetch_assign!/2
        (mailgun_logger 2022.3.0) lib/mailgun_logger_web/templates/layout/setup.html.eex:2:
MailgunLoggerWeb.LayoutView."setup.html"/1
        (phoenix_view 1.1.0) lib/phoenix/view.ex:473: Phoenix.View.render_to_iodata/3
        (phoenix 1.6.6) lib/phoenix/controller.ex:772: Phoenix.Controller.render_and_send/4
        (mailgun_logger 2022.3.0) lib/mailgun_logger_web/controllers/setup_controller.ex:1:
MailgunLoggerWeb.SetupController.action/2
        (mailgun_logger 2022.3.0) lib/mailgun_logger_web/controllers/setup_controller.ex:1:
MailgunLoggerWeb.SetupController.phoenix_controller_pipeline/2
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (mailgun_logger 2022.3.0) lib/plug/error_handler.ex:80: MailgunLoggerWeb.Router.call/2

I'm afraid, I don't know enough about the underlying technologies to determine what's happening.  If I'm missing something please ask and I will do my best to provide details.

**Comment by jeroenbourgois** [comment]
@BritHefty I will have a look asap. We have upgraded the project to the latest Phoenix version but I never checked the setup page!

**Comment by jeroenbourgois** [comment]
@BritHefty fixed on master.
