### ISSUE TITLE
Create index for a fresh start not working

### ISSUE THREAD

**Issue by m3techitopsadmin** [jackjoe/mailgun_logger#21]
> 16:45:33.115 [info] create index events_message_to_index
> ** (MyXQL.Error) (1071) Specified key was too long; max key length is 3072 bytes
>     (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
>     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
>     (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
>     (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
>     (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
>     (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
>     (stdlib 3.17) timer.erl:166: :timer.tc/1

**Comment by jeroenbourgois** [comment]
@m3techitopsadmin are you using the docker image, the docker compose stack? The error is clear, but for now I cannot reproduce what you have. What do you understand under 'a fresh start'?

**Comment by m3techitopsadmin** [comment]
I am using this:

> docker run -d -p 5050:5050 \
>   -e "ML_DB_USER=username" \
>   -e "ML_DB_PASSWORD=password" \
>   -e "ML_DB_NAME=mailgun_logger" \
>   -e "ML_DB_HOST=my_db_host" \
>   --name mailgun_logger jackjoe/mailgun_logger

It looks like the last change where the message_to field was increased is causing the index not to be created.

What i meant by fresh start is that, I deleted the db, the docker image and did a fresh pull so it builds the db schema from scratch.

**Comment by m3techitopsadmin** [comment]
I tired the docker compose locally...no issues. Could be due to the MySQL server in windows vs linux. I took a backup from the local MySQL to the windows MySQL and it is working now...i will close the ticket since it is a MySQL windows issue.

**Comment by m3techitopsadmin** [comment]
> I tired the docker compose locally...no issues. Could be due to the MySQL server in windows vs linux. I took a backup from the local MySQL to the windows MySQL and it is working now...you can close the ticket since it is a MySQL windows issue.

My bad, looks like i didn't clean up my previous docker compose volumes locally, I am having the same error with docker compose

**Comment by m3techitopsadmin** [comment]
Okay found a potential solution to the issue: The max allowed is 3072 bytes. The character set utfmb4 take 4 bytes per character. So the message_to field to be set to max 768.

**Comment by jeroenbourgois** [comment]
@m3techitopsadmin thanks for your input. But we should apply a different solution I think. Instead of altering the size of the field we should limit the size of the index. We have bumped into this problem in other projects, I will see how we handles it there and get back to you.

**Comment by jeroenbourgois** [comment]
A new release (2202.4.4) is out which fixed the index size. Being stupid, the version number does not really adhere to what is mentioned in the readme, I will fix that next time! ^^
