### ISSUE TITLE
Extract out to stand-alone elixir lib

### ISSUE THREAD

**Issue by cpursley** [jackjoe/mailgun_logger#3]
This is very timely! I'd love to see the logging bits extracted out into its own library so I can use it directly in an existing Phoenix app. Perhaps separate out the view related bits as well.

**Comment by jeroenbourgois** [comment]
@cpursley I will pick this up with @pierot and get back to you!

**Comment by jeroenbourgois** [comment]
Can you elaborate on what it is you want to do?

**Comment by jeroenbourgois** [comment]
@cpursley ?

**Comment by cpursley** [comment]
You can close this for now until I think through it a bit more. Thanks.

**Comment by jeroenbourgois** [comment]
Ok.
