### ISSUE TITLE
image name and volume dir in service db in docker-compose.yml seems wrong

### ISSUE THREAD

**Issue by mvoelz** [jackjoe/mailgun_logger#31]
https://github.com/jackjoe/mailgun_logger/blob/master/README.md?plain=1#L120 refers to `postgresql` it should be `postgres`

https://github.com/jackjoe/mailgun_logger/blob/master/README.md?plain=1#L128 refers to `/var/lib/mysql` it should be `/var/lib/postgresql/data`

**Comment by jeroenbourgois** [comment]
Thanks. I'll have a look, but it will probably be after the holidays.

**Comment by jeroenbourgois** [comment]
Fixed in latest version (2312.5.0)
