### ISSUE TITLE
column message_id in table events is too short

### ISSUE THREAD

**Issue by mvoelz** [jackjoe/mailgun_logger#32]
i saw errors stating that the column message_id in table events is too short (100) for some mails coming from proton.me
i fixed it with this query
`alter table events alter column message_id type varchar(255) using message_id::varchar(255)`

**Comment by jeroenbourgois** [comment]
Thanks! I'll have a look, but it will probably be after the holidays.

**Comment by jeroenbourgois** [comment]
Fixed in latest version (2312.5.0)
