### ISSUE TITLE
Cannot set `store_messages` to `false`

### ISSUE THREAD

**Issue by hkclark** [jackjoe/mailgun_logger#34]
Hello, 

Thanks for the tool.  I'm trying to run it in Docker compose but the `web` container always fails because `store_messages` seems to be hard coded to `true` but I don't want to use AWS.  I have never worked with Elixer, but it seems like it would be helpful if `config/config.exs` allowed you to set `store_messages` via an environment variable.  I'm guessing something like:

  ...
  store_messages: System.get_env("ML_STORE_MESSAGES") || true,
  ...

Apologies if my approach above is off base.

A few other things I noticed:

* The `README.md` uses `store_message` (without an "s") but `config.exs` seems to use `store_messages` (with an "s")
* Shouldn't the entrypoint in the `docker-compose.yml` use port 5432 vs 3306 (it seems the port didn't get updated when the project switched from MySQL to Postgres).

Thank you very much

**Comment by jeroenbourgois** [comment]
@hkclark thanks for your input, I will look into it ASAP.

**Comment by hkclark** [comment]
@jeroenbourgois Thank you!  Normally I would submit a pull request, but not being an Elixer guy, I wasn't positive on the suggested changes.  However, if it would be helpful for me to put one together let me know.

**Comment by jeroenbourgois** [comment]
@hkclark new version pushed, docker container should be build in the next minutes.

**Comment by hkclark** [comment]
> @hkclark new version pushed, docker container should be build in the next minutes.

Wonderful! Thank you!
