### ISSUE TITLE
Problems with display time

### ISSUE THREAD

**Issue by dickyangyi** [jackjoe/mailgun_logger#8]
Hello

What I belong to is CST time, I see on the mailgun log is 8 time, but the backstage pull time is UTC, I tried to change the mysql time zone into CST, but what mailgun_logger show or do I have any way to display the log as CST time so that I can proofread the log time correctly? Thank you!

**Comment by jeroenbourgois** [comment]
@dickyangyi your question is a bit confusing, but I think where you are heading. 

The data we get from the Mailgun API contains a `timestamp` field, which is a float. Before saving the event to the database, we convert that float into a `DateTime` struct in Elixir, which you can see [here](https://github.com/jackjoe/mailgun_logger/blob/96058dfd76642a9fe03506226905fd17cabfb9ec/lib/mailgun_logger/events):

```elixir
# MailgunLogger.Events
defp conv_event_timestamp(%{"timestamp" => timestamp}) do
  timestamp
  |> Kernel.trunc()
  |> DateTime.from_unix!()
end
```

The Unix timestamp should always be in UTC (though we cannot validate that from the Mailgun docs...). Thus the timestamp saved into the database also is in UTC. This is also best practice, the database should always contain UTC time.

Then in the display layer the correct timezone can be applied. Does this answer the question?

**Comment by dickyangyi** [comment]
I'm sorry, because it's been a vacation, I just saw it now. Thank you for your reply
